# -*- coding: utf-8 -*-
"""Emission-Congesiton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTR4vmbPNev_Rw2FJTQtjPaE2JvgE2rb
"""

#SYNTHETIC DATA FOR CONGESTION METRIC CALCULATION

import pandas as pd

df = pd.read_csv("/content/Travel_Times - Washington DC.csv")
df.head()

#Assumptions for Urban intersection dense area.
distance_km = 1.0  #Average OD distance in central DC
free_flow_speed = 60 #km/hr (urban free-flow speed)

df["travel_time_sec"] = df["Mean Travel Time (Seconds)"]

#Compute average speed.
df["average_speed_kmh"] = (distance_km/df["travel_time_sec"])*3600 #Convert it to hours.

#Compute free_flow travel time in seconds
df["free_flow_time_sec"] = (distance_km/free_flow_speed)*3600

#Compute delay (observed - free flow) in seconds
df["delay_sec"] = df["travel_time_sec"] - df["free_flow_time_sec"]

#Computing congestion index
df["congestion_index"] = (free_flow_speed - df["average_speed_kmh"])/free_flow_speed

#Sanithy check.
df[["Mean Travel Time (Seconds)", "average_speed_kmh","delay_sec","congestion_index"]].head()

df.to_csv("Travel_Times_DC_with_congestion.csv", index=False)

#SYNTHETIC DATA FOR EMISSION BASED CALCULATIONS

#IMPORTING LIBRARIES
import pandas as pd
import numpy as np

df = pd.read_csv("/content/Travel_Times_DC_with_congestion.csv")
df.head()

#Defining emission model constsnts(Assumptions)
a = 300 #constant term
b = -5 # linear speed term
c = 0.1 #quadratic speed term.

#Compute CO2 emissions per km.
df["co2_g_per_km"] = a+b*df["average_speed_kmh"]+c*(df["average_speed_kmh"]**2)

#OD=1.0 as we assumed.
#Emissions per OD trip
OD_distance_km = 1.0
df["co2_g_per_trip"] = df["co2_g_per_km"]*OD_distance_km

#Sanity check
df[["average_speed_kmh","co2_g_per_km","co2_g_per_trip"]].head()

df.to_csv("Travel_Times_DC_with_congestion_emissions.csv", index=False)

#EMISSION-CONGESTION DECOUPLING

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("/content/Travel_Times_DC_with_congestion_emissions.csv")
df.head()

#Defining the baseline
#Median traffic condition for both congestion and emission
baseline_congestion = df["congestion_index"].median()
baseline_emission = df["co2_g_per_km"].median()

#Computing percentage changes
#This represents if delta_congestion < 0 --> congestion reduces
#if delta_emission < 0 --> emission reduces
df["delta_congestion"] = (df["congestion_index"]-baseline_congestion)/baseline_congestion
df["delta_emission"] = (df["co2_g_per_km"] - baseline_emission)/baseline_emission

#Computing decoupling index
#This explains how emission respond to congestion changes
df["decoupling_index"] = df["delta_emission"]/df["delta_congestion"]

#Handling numerical issues like division-by-zero artifacts and unstable points
df = df.replace([np.inf, -np.inf],np.nan)
df = df.dropna(subset=["decoupling_index"])

#Classifying decouploing regimes
def classify_decoupling(row):
  if row["delta_congestion"] < 0 and row["delta_emission"] <0:
    return "Coupled"
  elif row["delta_congestion"]<0 and row["delta_emission"] > 0:
    return "Decoupled"
  else:
    return "Other"
df["decoupling_type"] = df.apply(classify_decoupling, axis = 1)

#Scatter plot
plt.figure(figsize=(7,6))
plt.scatter(df["delta_congestion"], df["delta_emission"], alpha=0.5)

plt.axhline(0, linestyle = "--")
plt.axvline(0, linestyle = "--")

plt.xlabel("Change in Congestion")
plt.ylabel("Change in emission")
plt.title("Emission-Congestion Decoupling Analaysis")

plt.show()
#Bottom-left --> Coupled(Both reduces)
#Bottom-right --> Decoupling (congestion reduces and emission increases)

#Summary statistics
df["decoupling_type"].value_counts(normalize=True) * 100

#Real world intersection-dense analysis is done.

#STARTING GRID BASED IMPLEMENTATIONS:
'''What we are simulating:

A 5×5 grid of intersections

OD trips crossing multiple intersections

Delay per intersection

Travel time = cruise time + signal delay

From that:

Speed

Emissions

Decoupling '''

#Preparing the environment for grid simulation
import pandas as pd
import numpy as np

#DEFINING GRID PARAMETERS.
grid_size = 5 #5x5 gris
block_length_km = 0.1 #100 meters per block
speed_limit = 40 #km/hr (urban)

#DEFINING OD TRIPS.
od_trips = {
    "short":2,
    "medium": 4,
     "long":6
}

#DEFINE INTERSECTION DELAY MODEL
#SIGNALIZED 4-WAY INTERSECTIONS WITH MODERATE DELAY
min_delay = 20 #seconds per intersection
max_delay = 40

#Generating Grid OD Dataset
grid_data = []
np.random.seed(42) #reproducibility
for trip_type, intersection in od_trips.items():
  distance_km = intersection * block_length_km
  for i in range(50):
    #Random delay per intersection
    delay_per_intersection = np.random.uniform(min_delay, max_delay)
    total_delay = intersection * delay_per_intersection

    #Cruise time(no intersection)
    cruise_time_Sec = (distance_km/speed_limit)

    #Total travel time
    total_time_sec = cruise_time_Sec+total_delay

    grid_data.append([trip_type,intersection,distance_km,total_delay,total_time_sec])

#Creating a datframe
df_grid = pd.DataFrame(grid_data,columns = ["trip_type", "num_intersections","distance_km","total_delay_sec","total_travel_time_sec"])
df_grid.head()

#Compute speed congestion metric using this.
df_grid["average_speed_kmph"] = (df_grid["distance_km"]/df_grid["total_travel_time_sec"])*3600

#ADD EMISSION MODEL
a = 300
b = -5
c = 0.1
df_grid["co2_g_per_km"] = (a+b*df_grid["average_speed_kmph"]+c*(df_grid["average_speed_kmph"]**2))

#Sanity check
df_grid.groupby("trip_type")[["average_speed_kmph","co2_g_per_km"]].mean()

#Saving the grid dataset
df_grid.to_csv("grid_signalized_4way.csv", index=False)

#GRID DECOUPLING
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df_grid = pd.read_csv("/content/grid_signalized_4way.csv")
df_grid.head()

#Defining baseline reference state
baseline_speed = df_grid["average_speed_kmph"].median()
baseline_emission = df_grid["co2_g_per_km"].median()

#Computing relative changes
df_grid["delta_speed"] = (df_grid["average_speed_kmph"] - baseline_speed)/baseline_speed
df_grid["delta_emission"] = (df_grid["co2_g_per_km"] - baseline_emission)/baseline_emission

#Computing decoupling index
df_grid["decoupling_index"] = (df_grid["delta_emission"]/df_grid["delta_speed"])
#DI < 0 → good decoupling

#DI ≈ 0 → weak coupling

#DI > 0 → bad decoupling

#Clean numerical issue
df_grid = df_grid.replace([np.inf, -np.inf], np.nan)
df_grid = df_grid.dropna(subset=["decoupling_index"])

#Classify decoupling regimes
def classify_grid_decoupling(row):
  if row["delta_speed"] > 0 and row["delta_emission"] < 0:
    return "Decoupled (GOOD)"
  elif row["delta_speed"] > 0 and row["delta_emission"] > 0:
    return "DeCoupled (BAD)"
  else:
    return "Coupled"
df_grid["decoupling_type"] = df_grid.apply(classify_grid_decoupling, axis = 1)

#Grid decoupling plot
plt.figure(figsize = (7,6))
plt.scatter(df_grid["delta_speed"], df_grid["delta_emission"], alpha = 0.6)
plt.axhline(0,linestyle = "--")
plt.axvline(0,linestyle = "--")
plt.xlabel("Change in speed (Congestion reduction)")
plt.ylabel("Change in emissions")
plt.title("Grid-Based Emission-Congestion Decoupling")
plt.show()

#Quantifying regimes
df_grid["decoupling_type"].value_counts(normalize=True) * 100

#Saving grid decoupling results
df_grid.to_csv("grid_signalized_4way_decoupling.csv", index = False)

#Define unsignalized delay model
#Delay model for unsignalized/minor intersections.
min_delay_unsignalized = 5
max_delay_unsignalized = 15

#Generating grid data
grid_data_unsignalized = []
np.random.seed(42)
for trip_type, intersection in od_trips.items():
  distance_km = intersection*block_length_km
  for i in range(50):
    delay_per_intersection = np.random.uniform(min_delay_unsignalized, max_delay_unsignalized)
    total_delay = intersection*delay_per_intersection
    cruise_time_Sec = (distance_km/speed_limit)*3600
    total_time_sec = cruise_time_Sec+total_delay
    grid_data_unsignalized.append([trip_type,intersection,distance_km,total_delay,total_time_sec])

#Create a dataframe
df_unsignalized = pd.DataFrame(grid_data_unsignalized,columns = ["trip_type", "num_intersections","distance_km","total_delay_sec","total_time_sec"])
df_unsignalized.head()

#Compute speed for unsignalized intersections
df_unsignalized["average_speed_kmph"] = (df_unsignalized["distance_km"]/df_unsignalized["total_time_sec"])*3600

#Computing emission
df_unsignalized["co2_g_per_km"] = (a+b*df_unsignalized["average_speed_kmph"]+c*(df_unsignalized["average_speed_kmph"]**2))

#Decoupling analysis unsignalized
baseline_speed_unsignalized = df_unsignalized["average_speed_kmph"].median()
baseline_emission_unsignalized = df_unsignalized["co2_g_per_km"].median()

df_unsignalized["delta_speed"] = (df_unsignalized["average_speed_kmph"]-baseline_speed_unsignalized)/baseline_speed_unsignalized
df_unsignalized["delta_emission"] = (df_unsignalized["co2_g_per_km"]-baseline_emission_unsignalized)/baseline_emission_unsignalized
df_unsignalized["decoupling_index"] = (df_unsignalized["delta_emission"]/df_unsignalized["delta_speed"])
df_unsignalized = df_unsignalized.replace([np.inf, -np.inf],np.nan)
df_unsignalized = df_unsignalized.dropna(subset=["decoupling_index"])

df_unsignalized["decoupling_type"] = df_unsignalized.apply(classify_grid_decoupling,axis = 1)

#Unsignalized decoupling plot
plt.figure(figsize=(7,6))
plt.scatter(
    df_unsignalized["delta_speed"],
    df_unsignalized["delta_emission"],
    alpha=0.6
)

plt.axhline(0, linestyle="--")
plt.axvline(0, linestyle="--")

plt.xlabel("Change in Speed")
plt.ylabel("Change in Emissions")
plt.title("Unsignalized Intersection Decoupling (Grid)")

plt.show()

#Sve the acquired results
df_unsignalized.to_csv("grid_unsignalized_decoupling.csv", index = False)

#DEFINING HIGH-VOLUME DELAY INTERSECTIONS
min_delay_hv = 50
max_delay_hv = 90

#Generate grid data
grid_data_hv = []
np.random.seed(42)
for trip_type, intersection in od_trips.items():
  distance_km = intersection*block_length_km
  for i in range(50):
    delay_per_intersection = np.random.uniform(min_delay_hv,max_delay_hv)
    total_delay = intersection*delay_per_intersection
    cruise_time_Sec = (distance_km/speed_limit)*3600
    total_time_sec = cruise_time_Sec+total_delay
    grid_data_hv.append([trip_type,intersection,distance_km,total_delay,total_time_sec])

#Create a dataframe
df_hv = pd.DataFrame(grid_data_hv, columns = ["trip_type","num_intersections","distance_km","total_delay_sec","total_time_sec"])
df_hv.head()

#Compute speed
df_hv["average_speed_kmh"] = (df_hv["distance_km"]/df_hv["total_time_sec"])*3600

#Compute emissions
df_hv["co2_g_per_km"] = (a+b*df_hv["average_speed_kmh"]+c*(df_hv["average_speed_kmh"]**2))

#DECOUPLING ANALYSIS FOR HIGH VOLUME
baseline_speed_hv = df_hv["average_speed_kmh"].median()
baseline_emission_hv = df_hv["co2_g_per_km"].median()
df_hv["delta_speed"] = (df_hv["average_speed_kmh"]-baseline_speed_hv)/baseline_speed_hv
df_hv["delta_emission"] = (df_hv["co2_g_per_km"]-baseline_emission_hv)/baseline_emission_hv
df_hv["decoupling_index"] = (df_hv["delta_emission"]/df_hv["delta_speed"])
df_hv = df_hv.replace([np.inf,-np.inf],np.nan)
df_hv = df_hv.dropna(subset=["decoupling_index"])

#CLASSIFY HIGH VOLUME BEHAVIOUR
df_hv["decoupling_type"] = df_hv.apply(classify_grid_decoupling,axis=1)

#High volume decoupling plot
plt.figure(figsize=(7,6))
plt.scatter(
    df_hv["delta_speed"],
    df_hv["delta_emission"],
    alpha=0.6
)

plt.axhline(0, linestyle="--")
plt.axvline(0, linestyle="--")

plt.xlabel("Change in Speed")
plt.ylabel("Change in Emissions")
plt.title("High-Volume Intersection Decoupling (Grid)")

plt.show()

#SAVING FINAL DATASET
df_hv.to_csv("grid_high_volume_decoupling.csv",index = False)

#BRINGING ALL RESULTS INTO ONE WORKSPACE FOR COMPARISON
import pandas as pd
#Loading all syntehtic datasets
df_dc = pd.read_csv("Travel_Times_DC_with_congestion_emissions.csv")
df_grid = pd.read_csv("grid_signalized_4way_decoupling.csv")
df_unsig = pd.read_csv("grid_unsignalized_decoupling.csv")
df_hv = pd.read_csv("grid_high_volume_decoupling.csv")

#STANDARDIZE COLUMNS
def extract_metrics(df, label):
  return pd.DataFrame({"case": label, "average_speed":df['average_speed_kmh'],"co2":df["co2_g_per_km"],"decoupling_type":df["decoupling_type"]})

# Rename average_speed_kmph to average_speed_kmh for consistency in df_grid and df_unsig
df_grid = df_grid.rename(columns={'average_speed_kmph': 'average_speed_kmh'})
df_unsig = df_unsig.rename(columns={'average_speed_kmph': 'average_speed_kmh'})

df_compare = pd.concat([
    extract_metrics(df, "Washington DC (Real)"),
    extract_metrics(df_grid, "Grid Signalized"),
    extract_metrics(df_unsig, "Grid Unsignalized"),
    extract_metrics(df_hv, "Grid High Volume")
])

#SUMMARY TABLE
summary = df_compare.groupby("case").agg({"average_speed":"mean","co2":"mean"}).round(2)
summary

# DECOUPLING DISTRIBUTION
decoupling_stats = (
    df_compare
    .groupby(["case", "decoupling_type"])
    .size()
    .unstack(fill_value=0)
)

decoupling_stats

#CONVERT DECOUPLING DISTRIBUTION TO PERCENTAGES
decoupling_percent = decoupling_stats.div(
    decoupling_stats.sum(axis=1), axis=0
) * 100

decoupling_percent.round(1)

#COMPARISON PLOT
import matplotlib.pyplot as plt

summary["average_speed"].plot(
    kind="bar",
    title="Average Speed Across Network Types",
    ylabel="km/h",
    figsize=(7,4)
)
plt.show()

#ML DATASETS TO TRAIN XGBOOST.

import pandas as pd

# Load datasets
df_dc = pd.read_csv("Travel_Times_DC_with_congestion_emissions.csv")
df_grid = pd.read_csv("grid_signalized_4way_decoupling.csv")
df_unsignalized = pd.read_csv("grid_unsignalized_decoupling.csv")
df_hv = pd.read_csv("grid_high_volume_decoupling.csv")

#ADD IDENTIFIERS
df_dc["network_type"] = "Real_DC"
df_grid["network_type"] = "Grid_Signalized"
df_unsignalized["network_type"] = "Grid_Unsignalized"
df_hv["network_type"] = "Grid_HighVolume"

#ADDING INTERSECTION TYPE
df_dc["intersection_type"] = "Urban_Mixed"
df_grid["intersection_type"] = "Signalized"
df_unsignalized["intersection_type"] = "Unsignalized"
df_hv["intersection_type"] = "HighVolume"

#STADARDIZE REQUIRED COLUMNS
selected_columns = [
    "average_speed_kmh",
    "congestion_index",
    "total_delay_sec",
    "num_intersections",
    "distance_km",
    "intersection_type",
    "network_type",
    "decoupling_type"
]

def select_available_columns(df, cols):
    return df[[c for c in cols if c in df.columns]]

df_dc = select_available_columns(df_dc, selected_columns)
df_grid = select_available_columns(df_grid, selected_columns)
df_unsignalized = select_available_columns(df_unsig, selected_columns)
df_hv = select_available_columns(df_hv, selected_columns)

#COMBINE INTO ONE ML DATASET
df_ml = pd.concat([df_dc, df_grid, df_unsignalized, df_hv], ignore_index=True)
df_ml.head()

#CREATE ML LABEL
df_ml["decoupled_label"] = df_ml["decoupling_type"].apply(
    lambda x: 1 if pd.notna(x) and "Decoupled" in x else 0
)

#HANDLE CATEGORICAL VALUES
df_ml_encoded = pd.get_dummies(
    df_ml,
    columns=["intersection_type", "network_type"],
    drop_first=True
)

#FINAL SANITY CHECK
df_ml_encoded.info()

#MISSING VALUES
df_ml_encoded = df_ml_encoded.dropna()

#SAVE ML DATASET
df_ml_encoded.to_csv("ml_dataset_xgboost.csv", index=False)

df_ml_encoded.head()

import pandas as pd
df_ml_encoded = pd.get_dummies(
    df_ml,
    columns=["intersection_type", "network_type"],
    drop_first=True
)

df_ml_encoded.isnull().sum()

df_ml_encoded = df_ml_encoded.fillna(0)

df_ml_encoded.shape

df_ml_encoded.head()
df_ml_encoded.sample(5)

df_ml_encoded.to_csv("ml_dataset_xgboost.csv", index=False)

df_ml_encoded.shape

df_ml_encoded.head()
df_ml_encoded.sample(5)

# Features = everything except labels
X = df_ml_encoded.drop(columns=["decoupling_type", "decoupled_label"])

# Target = what we want to predict
y = df_ml_encoded["decoupled_label"]

print(X.shape, y.shape)

!pip install xgboost

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=150,
    max_depth=4,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

#EVALUATING PERFORMANCE
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

confusion_matrix(y_test, y_pred)

#FEATURE IMPORTANCE FOR DECOUPLING
import matplotlib.pyplot as plt
import numpy as np

importance = xgb_model.feature_importances_
feature_names = X.columns

sorted_idx = np.argsort(importance)

plt.figure(figsize=(8,6))
plt.barh(feature_names[sorted_idx], importance[sorted_idx])
plt.title("XGBoost Feature Importance for Decoupling Prediction")
plt.xlabel("Importance Score")
plt.show()

#VISUALIZATION MODEL
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("XGBoost Decoupling Prediction Confusion Matrix")
plt.show()

import joblib
joblib.dump(xgb_model, "xgboost_decoupling_model.pkl")

#RESULT TABLE
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
print("Model Accuracy:", acc)

print(X.columns)

import pandas as pd

importance_df = pd.DataFrame({
    "feature": X.columns,
    "importance": xgb_model.feature_importances_
}).sort_values(by="importance", ascending=False)

importance_df.head(10)

!pip install streamlit
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# from xgboost import XGBClassifier
# from sklearn.model_selection import train_test_split
# 
# st.title("Emission–Congestion Decoupling Analysis Dashboard")
# 
# st.write("This dashboard demonstrates the relationship between traffic congestion and emissions using machine learning.")
# 
# # Generate a sample dataset (replace with your dataset if needed)
# np.random.seed(42)
# 
# data = pd.DataFrame({
#     "average_speed_kmh": np.random.uniform(5, 60, 300),
#     "congestion_index": np.random.uniform(0.5, 2.5, 300),
#     "total_delay_sec": np.random.uniform(10, 300, 300),
#     "num_intersections": np.random.randint(1, 10, 300),
#     "distance_km": np.random.uniform(0.5, 10, 300)
# })
# 
# # Emission model
# def emission_model(speed):
#     a = 0.02
#     b = -1.5
#     c = 300
#     return a*(speed**2) + b*speed + c
# 
# data["co2"] = data["average_speed_kmh"].apply(emission_model)
# 
# # Create decoupling label
# data["decoupled"] = np.where(data["co2"] < data["co2"].mean(), 1, 0)
# 
# st.subheader("Dataset Preview")
# st.dataframe(data.head())
# 
# # Plot relationship
# st.subheader("Emission vs Congestion Visualization")
# 
# fig, ax = plt.subplots()
# ax.scatter(data["congestion_index"], data["co2"])
# ax.set_xlabel("Congestion Index")
# ax.set_ylabel("Estimated Emission")
# st.pyplot(fig)
# 
# # Machine Learning Model
# X = data[["average_speed_kmh","congestion_index","total_delay_sec","num_intersections","distance_km"]]
# y = data["decoupled"]
# 
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
# 
# model = XGBClassifier()
# model.fit(X_train,y_train)
# 
# st.subheader("Predict Decoupling")
# 
# speed = st.slider("Average Speed",5,80,30)
# congestion = st.slider("Congestion Index",0.5,3.0,1.2)
# delay = st.slider("Total Delay",0,500,100)
# intersections = st.slider("Number of Intersections",1,15,5)
# distance = st.slider("Distance (km)",1,20,5)
# 
# if st.button("Predict"):
# 
#     input_data = np.array([[speed, congestion, delay, intersections, distance]])
# 
#     prediction = model.predict(input_data)
# 
#     if prediction[0] == 1:
#         st.success("Decoupled: Emission may decrease with congestion change")
#     else:
#         st.warning("Coupled: Emission follows congestion pattern")
# 
# # Feature importance
# st.subheader("Feature Importance")
# 
# importance = model.feature_importances_
# 
# features = X.columns
# 
# fig2, ax2 = plt.subplots()
# ax2.barh(features, importance)
# st.pyplot(fig2)

!pip install streamlit
!npm install -g localtunnel

!streamlit run app.py &>/dev/null &

